name: direct_select_flutter
description: Direct Select Widget Implementation inspired by https://dribbble.com/shots/3876250-DirectSelect-Dropdown-ux
homepage: https://github.com/LanarsInc/direct-select-flutter
version: 1.1.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true